In [1]:
# Cell 1 — Config
SEED = 42

# Paths (change to your actual CSV paths)
TASHBEEH_CSV = "tashbeeh_dataset.csv"
NON_TASHBEEH_CSV = "non_tashbeeh_random_sample.csv"

TEXT_COL = "البيت_الكامل"   # or "التعبير البلاغي" if you prefer
LABEL_COL = "label"

# Split
TEST_SIZE = 0.15
VAL_SIZE  = 0.15

# Model choice (hardcode one of these)
MODEL_ID = 4
MODEL_CANDIDATES = {
    1: "aubmindlab/bert-base-arabertv02",
    2: "CAMeL-Lab/bert-base-arabic-camelbert-mix",
    3: "CAMeL-Lab/bert-base-arabic-camelbert-ca",
    4: "aubmindlab/bert-large-arabertv2"
}
MODEL_NAME = MODEL_CANDIDATES[MODEL_ID]

# Training
MAX_LEN = 96
BATCH_SIZE = 8
EPOCHS = 20
LR = 2e-5
WEIGHT_DECAY = 0.01
WARMUP_RATIO = 0.06

OUTPUT_DIR = f"runs_tashbeeh/{MODEL_NAME.replace('/','_')}"
print("Model:", MODEL_NAME)
print("Output:", OUTPUT_DIR)

Model: aubmindlab/bert-large-arabertv2
Output: runs_tashbeeh/aubmindlab_bert-large-arabertv2

In [2]:
# Cell 2 — Imports
import os, random
import numpy as np
import pandas as pd

import torch
from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding,
)

import evaluate

C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\USER\miniconda3\envs\torch-gpu\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
c:\Users\USER\miniconda3\envs\torch-gpu\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
c:\Users\USER\miniconda3\envs\torch-gpu\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(

In [3]:
# Cell 3 — Repro + Device
def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

seed_everything(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device, "| cuda:", torch.cuda.is_available())

device: cuda | cuda: True

In [4]:
# Cell 4 — Load + Label
df_pos = pd.read_csv(TASHBEEH_CSV)
df_neg = pd.read_csv(NON_TASHBEEH_CSV)

df_pos = df_pos[[TEXT_COL]].copy()
df_neg = df_neg[[TEXT_COL]].copy()

df_pos[LABEL_COL] = 1
df_neg[LABEL_COL] = 0

df = pd.concat([df_pos, df_neg], ignore_index=True)
df[TEXT_COL] = df[TEXT_COL].astype(str).str.strip()
df = df[df[TEXT_COL].str.len() > 0].reset_index(drop=True)

print("Total:", df.shape)
print(df[LABEL_COL].value_counts())
df.head()

Total: (1182, 2)
label
1    591
0    591
Name: count, dtype: int64

                                        البيت_الكامل  label
0  أهُمُّ بِشَيْءٍ واللَّيالي كأنَّهَا تُطارِدُنِ...      1
1  تَثَنَّى عَلى قَدْرِ الطِّعانِ كأنَّما مَفاصِل...      1
2  وَلمَّا رأيْتُ النَّاسَ دُونَ مَحَلِّهِ تَيَقّ...      1
3  مُخَضَّبَةٌ والْقَوْمُ صَرْعَى كأنَّها وَإنْ ل...      1
4  تُنَكِّسِهُمْ والسَّابِقاتُ جِبالُهُمْ وَتَطْع...      1

In [5]:
# Cell — Train/Val/Test split (stratified) with ClassLabel casting
from datasets import Features, Value, ClassLabel

# Build Dataset with explicit features (label as ClassLabel)
features = Features({
    TEXT_COL: Value("string"),
    LABEL_COL: ClassLabel(names=["non_tashbeeh", "tashbeeh"]),
})

full_ds = Dataset.from_pandas(
    df[[TEXT_COL, LABEL_COL]].reset_index(drop=True),
    features=features
)

# Split out test
tmp = full_ds.train_test_split(
    test_size=TEST_SIZE,
    seed=SEED,
    stratify_by_column=LABEL_COL
)
train_val_ds, test_ds = tmp["train"], tmp["test"]

# Split train/val
val_relative = VAL_SIZE / (1.0 - TEST_SIZE)
tmp2 = train_val_ds.train_test_split(
    test_size=val_relative,
    seed=SEED,
    stratify_by_column=LABEL_COL
)
train_ds, val_ds = tmp2["train"], tmp2["test"]

print("Train:", len(train_ds), "Val:", len(val_ds), "Test:", len(test_ds))

def balance(ds):
    y = np.array(ds[LABEL_COL])
    return {0: int((y==0).sum()), 1: int((y==1).sum())}

print("Train balance:", balance(train_ds))
print("Val balance  :", balance(val_ds))
print("Test balance :", balance(test_ds))
print("Label names:", full_ds.features[LABEL_COL].names)

Train: 826 Val: 178 Test: 178
Train balance: {0: 413, 1: 413}
Val balance  : {0: 89, 1: 89}
Test balance : {0: 89, 1: 89}
Label names: ['non_tashbeeh', 'tashbeeh']

In [6]:
# Cell 5 — Tokenize train/val/test (using train_ds/val_ds/test_ds)
# ---------------------------------------------------------------
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_batch(batch):
    return tokenizer(
        batch[TEXT_COL],
        truncation=True,
        max_length=MAX_LEN,
    )

# Tokenize; keep label column for now
train_tok = train_ds.map(tokenize_batch, batched=True)
val_tok   = val_ds.map(tokenize_batch, batched=True)
test_tok  = test_ds.map(tokenize_batch, batched=True)

# Remove text column after tokenization to save memory
train_tok = train_tok.remove_columns([TEXT_COL])
val_tok   = val_tok.remove_columns([TEXT_COL])
test_tok  = test_tok.remove_columns([TEXT_COL])

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# Trainer expects label column to be named "labels"
train_tok = train_tok.rename_column(LABEL_COL, "labels")
val_tok   = val_tok.rename_column(LABEL_COL, "labels")
test_tok  = test_tok.rename_column(LABEL_COL, "labels")

# Make sure dataset returns torch tensors
train_tok.set_format(type="torch")
val_tok.set_format(type="torch")
test_tok.set_format(type="torch")

print("Keys:", train_tok.column_names)
print("Example:", {k: (v.shape if hasattr(v, "shape") else v) for k, v in train_tok[0].items()})

c:\Users\USER\miniconda3\envs\torch-gpu\lib\site-packages\huggingface_hub\file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Map: 100%|██████████| 826/826 [00:00<00:00, 18375.48 examples/s]
Map: 100%|██████████| 178/178 [00:00<00:00, 15565.23 examples/s]
Map: 100%|██████████| 178/178 [00:00<00:00, 15429.80 examples/s]

Keys: ['labels', 'input_ids', 'token_type_ids', 'attention_mask']
Example: {'labels': torch.Size([]), 'input_ids': torch.Size([13]), 'token_type_ids': torch.Size([13]), 'attention_mask': torch.Size([13])}

In [7]:
# Cell 6 — Metrics (no sklearn)
import numpy as np
import evaluate

acc = evaluate.load("accuracy")
prec = evaluate.load("precision")
rec = evaluate.load("recall")
f1 = evaluate.load("f1")
cm = evaluate.load("confusion_matrix")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)

    out = {}
    out["accuracy"] = acc.compute(predictions=preds, references=labels)["accuracy"]
    out["precision_pos"] = prec.compute(predictions=preds, references=labels, average="binary")["precision"]
    out["recall_pos"] = rec.compute(predictions=preds, references=labels, average="binary")["recall"]
    out["f1_pos"] = f1.compute(predictions=preds, references=labels, average="binary")["f1"]

    cmat = cm.compute(predictions=preds, references=labels, labels=[0, 1])["confusion_matrix"]
    out["tn"], out["fp"] = int(cmat[0][0]), int(cmat[0][1])
    out["fn"], out["tp"] = int(cmat[1][0]), int(cmat[1][1])
    return out

In [8]:
# Cell 6.5 — Build model (Trainer will move it to GPU automatically)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

c:\Users\USER\miniconda3\envs\torch-gpu\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at aubmindlab/bert-large-arabertv2 and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [9]:
# Cell 7 — TrainingArguments + Trainer (transformers 4.35.2)
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    learning_rate=LR,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    num_train_epochs=EPOCHS,
    weight_decay=WEIGHT_DECAY,
    warmup_ratio=WARMUP_RATIO,

    evaluation_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="f1_pos",
    greater_is_better=True,

    logging_strategy="steps",
    logging_steps=50,
    report_to="none",

    fp16=torch.cuda.is_available(),   # True on GPU
    seed=SEED,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tok,
    eval_dataset=val_tok,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)
print("Trainer ready.")

c:\Users\USER\miniconda3\envs\torch-gpu\lib\site-packages\accelerate\accelerator.py:439: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(**kwargs)

Trainer ready.

In [10]:
print("torch:", torch.__version__)
print("cuda available:", torch.cuda.is_available())
print("torch cuda version:", torch.version.cuda)
print("gpu count:", torch.cuda.device_count())
if torch.cuda.is_available():
    print("gpu:", torch.cuda.get_device_name(0))
    print("cap:", torch.cuda.get_device_capability(0))

torch: 2.5.1
cuda available: True
torch cuda version: 12.1
gpu count: 1
gpu: NVIDIA GeForce RTX 3060 Ti
cap: (8, 6)

In [11]:
# Cell 8 — Train
# ---------------------------------------------------------------
train_result = trainer.train()
train_result

  0%|          | 0/2080 [00:00<?, ?it/s]You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
  2%|▏         | 50/2080 [00:21<17:15,  1.96it/s]

{'loss': 0.8215, 'learning_rate': 7.04e-06, 'epoch': 0.48}

  5%|▍         | 100/2080 [00:39<13:28,  2.45it/s]

{'loss': 0.7419, 'learning_rate': 1.4720000000000001e-05, 'epoch': 0.96}

  5%|▌         | 104/2080 [00:40<09:04,  3.63it/s]c:\Users\USER\miniconda3\envs\torch-gpu\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

  5%|▌         | 104/2080 [00:42<09:04,  3.63it/s]

{'eval_loss': 0.7181752920150757, 'eval_accuracy': 0.5, 'eval_precision_pos': 0.0, 'eval_recall_pos': 0.0, 'eval_f1_pos': 0.0, 'eval_tn': 89, 'eval_fp': 0, 'eval_fn': 89, 'eval_tp': 0, 'eval_runtime': 1.0937, 'eval_samples_per_second': 162.757, 'eval_steps_per_second': 21.03, 'epoch': 1.0}

  7%|▋         | 150/2080 [01:09<12:12,  2.64it/s]

{'loss': 0.7207, 'learning_rate': 1.9846547314578007e-05, 'epoch': 1.44}

 10%|▉         | 200/2080 [01:29<12:41,  2.47it/s]

{'loss': 0.712, 'learning_rate': 1.9335038363171357e-05, 'epoch': 1.92}

 10%|█         | 208/2080 [01:33<10:36,  2.94it/s]

{'eval_loss': 0.7330445647239685, 'eval_accuracy': 0.5, 'eval_precision_pos': 0.5, 'eval_recall_pos': 0.9775280898876404, 'eval_f1_pos': 0.6615969581749049, 'eval_tn': 2, 'eval_fp': 87, 'eval_fn': 2, 'eval_tp': 87, 'eval_runtime': 1.0819, 'eval_samples_per_second': 164.518, 'eval_steps_per_second': 21.258, 'epoch': 2.0}

 12%|█▏        | 250/2080 [02:08<12:26,  2.45it/s]

{'loss': 0.7248, 'learning_rate': 1.8823529411764708e-05, 'epoch': 2.4}

 14%|█▍        | 300/2080 [02:29<16:01,  1.85it/s]

{'loss': 0.7164, 'learning_rate': 1.8312020460358058e-05, 'epoch': 2.88}

 15%|█▌        | 312/2080 [02:38<20:49,  1.42it/s]

{'eval_loss': 0.7021881937980652, 'eval_accuracy': 0.5337078651685393, 'eval_precision_pos': 0.55, 'eval_recall_pos': 0.3707865168539326, 'eval_f1_pos': 0.4429530201342282, 'eval_tn': 62, 'eval_fp': 27, 'eval_fn': 56, 'eval_tp': 33, 'eval_runtime': 1.5918, 'eval_samples_per_second': 111.823, 'eval_steps_per_second': 14.449, 'epoch': 3.0}

 17%|█▋        | 350/2080 [03:45<09:56,  2.90it/s]

{'loss': 0.7306, 'learning_rate': 1.780051150895141e-05, 'epoch': 3.37}

 19%|█▉        | 400/2080 [04:02<10:46,  2.60it/s]

{'loss': 0.7275, 'learning_rate': 1.728900255754476e-05, 'epoch': 3.85}

 20%|██        | 416/2080 [04:10<11:23,  2.44it/s]

{'eval_loss': 0.7023637890815735, 'eval_accuracy': 0.5, 'eval_precision_pos': 0.5, 'eval_recall_pos': 0.8876404494382022, 'eval_f1_pos': 0.6396761133603239, 'eval_tn': 10, 'eval_fp': 79, 'eval_fn': 10, 'eval_tp': 79, 'eval_runtime': 1.0527, 'eval_samples_per_second': 169.09, 'eval_steps_per_second': 21.849, 'epoch': 4.0}

 22%|██▏       | 450/2080 [05:07<10:24,  2.61it/s]

{'loss': 0.7173, 'learning_rate': 1.677749360613811e-05, 'epoch': 4.33}

 24%|██▍       | 500/2080 [05:25<10:31,  2.50it/s]

{'loss': 0.7204, 'learning_rate': 1.626598465473146e-05, 'epoch': 4.81}

 25%|██▌       | 520/2080 [05:34<09:22,  2.77it/s]

{'eval_loss': 0.6983080506324768, 'eval_accuracy': 0.4943820224719101, 'eval_precision_pos': 0.0, 'eval_recall_pos': 0.0, 'eval_f1_pos': 0.0, 'eval_tn': 88, 'eval_fp': 1, 'eval_fn': 89, 'eval_tp': 0, 'eval_runtime': 1.1569, 'eval_samples_per_second': 153.856, 'eval_steps_per_second': 19.88, 'epoch': 5.0}

 26%|██▋       | 550/2080 [05:59<11:14,  2.27it/s]

{'loss': 0.7102, 'learning_rate': 1.575447570332481e-05, 'epoch': 5.29}

 29%|██▉       | 600/2080 [06:21<14:00,  1.76it/s]

{'loss': 0.719, 'learning_rate': 1.524296675191816e-05, 'epoch': 5.77}

 30%|███       | 624/2080 [06:35<09:48,  2.47it/s]

{'eval_loss': 0.6966127753257751, 'eval_accuracy': 0.4943820224719101, 'eval_precision_pos': 0.0, 'eval_recall_pos': 0.0, 'eval_f1_pos': 0.0, 'eval_tn': 88, 'eval_fp': 1, 'eval_fn': 89, 'eval_tp': 0, 'eval_runtime': 1.6546, 'eval_samples_per_second': 107.577, 'eval_steps_per_second': 13.9, 'epoch': 6.0}

 31%|███▏      | 650/2080 [07:42<10:38,  2.24it/s]

{'loss': 0.7057, 'learning_rate': 1.4731457800511511e-05, 'epoch': 6.25}

 34%|███▎      | 700/2080 [08:07<11:53,  1.93it/s]

{'loss': 0.7074, 'learning_rate': 1.4219948849104861e-05, 'epoch': 6.73}

 35%|███▌      | 728/2080 [08:22<09:32,  2.36it/s]

{'eval_loss': 0.6970489025115967, 'eval_accuracy': 0.5, 'eval_precision_pos': 0.5, 'eval_recall_pos': 1.0, 'eval_f1_pos': 0.6666666666666666, 'eval_tn': 0, 'eval_fp': 89, 'eval_fn': 0, 'eval_tp': 89, 'eval_runtime': 1.183, 'eval_samples_per_second': 150.461, 'eval_steps_per_second': 19.442, 'epoch': 7.0}

 36%|███▌      | 751/2080 [08:41<07:05,  3.13it/s]

{'loss': 0.7339, 'learning_rate': 1.3708439897698212e-05, 'epoch': 7.21}

 38%|███▊      | 800/2080 [09:00<08:04,  2.64it/s]

{'loss': 0.7, 'learning_rate': 1.3196930946291562e-05, 'epoch': 7.69}

 40%|████      | 832/2080 [09:14<08:16,  2.51it/s]

{'eval_loss': 0.701424241065979, 'eval_accuracy': 0.5, 'eval_precision_pos': 0.5, 'eval_recall_pos': 1.0, 'eval_f1_pos': 0.6666666666666666, 'eval_tn': 0, 'eval_fp': 89, 'eval_fn': 0, 'eval_tp': 89, 'eval_runtime': 1.0135, 'eval_samples_per_second': 175.631, 'eval_steps_per_second': 22.694, 'epoch': 8.0}

 41%|████      | 850/2080 [09:32<06:58,  2.94it/s]

{'loss': 0.7113, 'learning_rate': 1.2685421994884913e-05, 'epoch': 8.17}

 43%|████▎     | 900/2080 [09:50<05:58,  3.29it/s]

{'loss': 0.7097, 'learning_rate': 1.2173913043478263e-05, 'epoch': 8.65}

 45%|████▌     | 936/2080 [10:05<06:43,  2.83it/s]

{'eval_loss': 0.6947803497314453, 'eval_accuracy': 0.4943820224719101, 'eval_precision_pos': 0.0, 'eval_recall_pos': 0.0, 'eval_f1_pos': 0.0, 'eval_tn': 88, 'eval_fp': 1, 'eval_fn': 89, 'eval_tp': 0, 'eval_runtime': 1.1309, 'eval_samples_per_second': 157.401, 'eval_steps_per_second': 20.338, 'epoch': 9.0}

 46%|████▌     | 950/2080 [10:50<08:31,  2.21it/s]

{'loss': 0.6918, 'learning_rate': 1.1662404092071614e-05, 'epoch': 9.13}

 48%|████▊     | 1000/2080 [11:11<08:10,  2.20it/s]

{'loss': 0.7193, 'learning_rate': 1.1150895140664964e-05, 'epoch': 9.62}

 50%|█████     | 1040/2080 [11:28<06:27,  2.68it/s]

{'eval_loss': 0.7253760695457458, 'eval_accuracy': 0.5, 'eval_precision_pos': 0.5, 'eval_recall_pos': 0.11235955056179775, 'eval_f1_pos': 0.1834862385321101, 'eval_tn': 79, 'eval_fp': 10, 'eval_fn': 79, 'eval_tp': 10, 'eval_runtime': 1.0183, 'eval_samples_per_second': 174.8, 'eval_steps_per_second': 22.587, 'epoch': 10.0}

 50%|█████     | 1050/2080 [11:45<10:03,  1.71it/s]

{'loss': 0.7271, 'learning_rate': 1.0639386189258314e-05, 'epoch': 10.1}

 53%|█████▎    | 1100/2080 [12:05<05:22,  3.04it/s]

{'loss': 0.709, 'learning_rate': 1.0127877237851665e-05, 'epoch': 10.58}

 55%|█████▌    | 1144/2080 [12:23<06:05,  2.56it/s]

{'eval_loss': 0.7061945796012878, 'eval_accuracy': 0.4943820224719101, 'eval_precision_pos': 0.0, 'eval_recall_pos': 0.0, 'eval_f1_pos': 0.0, 'eval_tn': 88, 'eval_fp': 1, 'eval_fn': 89, 'eval_tp': 0, 'eval_runtime': 1.0335, 'eval_samples_per_second': 172.232, 'eval_steps_per_second': 22.255, 'epoch': 11.0}

 55%|█████▌    | 1150/2080 [12:38<16:45,  1.08s/it]

{'loss': 0.732, 'learning_rate': 9.616368286445014e-06, 'epoch': 11.06}

 58%|█████▊    | 1200/2080 [12:57<04:50,  3.03it/s]

{'loss': 0.6933, 'learning_rate': 9.104859335038364e-06, 'epoch': 11.54}

 60%|██████    | 1248/2080 [13:16<04:37,  3.00it/s]

{'eval_loss': 0.6942893266677856, 'eval_accuracy': 0.5, 'eval_precision_pos': 0.5, 'eval_recall_pos': 0.8876404494382022, 'eval_f1_pos': 0.6396761133603239, 'eval_tn': 10, 'eval_fp': 79, 'eval_fn': 10, 'eval_tp': 79, 'eval_runtime': 1.1855, 'eval_samples_per_second': 150.15, 'eval_steps_per_second': 19.401, 'epoch': 12.0}

 60%|██████    | 1250/2080 [14:02<2:18:11,  9.99s/it]

{'loss': 0.6923, 'learning_rate': 8.593350383631714e-06, 'epoch': 12.02}

 62%|██████▎   | 1300/2080 [14:21<04:02,  3.22it/s]

{'loss': 0.7015, 'learning_rate': 8.081841432225065e-06, 'epoch': 12.5}

 65%|██████▍   | 1350/2080 [14:40<04:55,  2.47it/s]

{'loss': 0.7076, 'learning_rate': 7.570332480818415e-06, 'epoch': 12.98}

 65%|██████▌   | 1352/2080 [14:42<04:54,  2.47it/s]

{'eval_loss': 0.695540189743042, 'eval_accuracy': 0.5, 'eval_precision_pos': 0.5, 'eval_recall_pos': 1.0, 'eval_f1_pos': 0.6666666666666666, 'eval_tn': 0, 'eval_fp': 89, 'eval_fn': 0, 'eval_tp': 89, 'eval_runtime': 1.0662, 'eval_samples_per_second': 166.951, 'eval_steps_per_second': 21.572, 'epoch': 13.0}

 67%|██████▋   | 1401/2080 [15:13<04:06,  2.76it/s]

{'loss': 0.6979, 'learning_rate': 7.058823529411766e-06, 'epoch': 13.46}

 70%|██████▉   | 1450/2080 [15:31<04:05,  2.57it/s]

{'loss': 0.7014, 'learning_rate': 6.547314578005116e-06, 'epoch': 13.94}

 70%|███████   | 1456/2080 [15:35<03:14,  3.21it/s]

{'eval_loss': 0.6939710974693298, 'eval_accuracy': 0.5056179775280899, 'eval_precision_pos': 0.5031847133757962, 'eval_recall_pos': 0.8876404494382022, 'eval_f1_pos': 0.6422764227642277, 'eval_tn': 11, 'eval_fp': 78, 'eval_fn': 10, 'eval_tp': 79, 'eval_runtime': 1.1996, 'eval_samples_per_second': 148.388, 'eval_steps_per_second': 19.174, 'epoch': 14.0}

 72%|███████▏  | 1501/2080 [16:40<02:55,  3.29it/s]

{'loss': 0.7061, 'learning_rate': 6.035805626598466e-06, 'epoch': 14.42}

 75%|███████▍  | 1551/2080 [16:59<02:49,  3.12it/s]

{'loss': 0.7224, 'learning_rate': 5.524296675191816e-06, 'epoch': 14.9}

 75%|███████▌  | 1560/2080 [17:03<03:36,  2.41it/s]c:\Users\USER\miniconda3\envs\torch-gpu\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

 75%|███████▌  | 1560/2080 [17:04<03:36,  2.41it/s]

{'eval_loss': 0.6982038021087646, 'eval_accuracy': 0.5, 'eval_precision_pos': 0.0, 'eval_recall_pos': 0.0, 'eval_f1_pos': 0.0, 'eval_tn': 89, 'eval_fp': 0, 'eval_fn': 89, 'eval_tp': 0, 'eval_runtime': 0.9956, 'eval_samples_per_second': 178.782, 'eval_steps_per_second': 23.101, 'epoch': 15.0}

 77%|███████▋  | 1600/2080 [17:52<03:07,  2.56it/s]

{'loss': 0.7094, 'learning_rate': 5.012787723785167e-06, 'epoch': 15.38}

 79%|███████▉  | 1650/2080 [18:11<03:03,  2.34it/s]

{'loss': 0.7135, 'learning_rate': 4.501278772378517e-06, 'epoch': 15.87}

 80%|████████  | 1664/2080 [18:17<02:16,  3.04it/s]c:\Users\USER\miniconda3\envs\torch-gpu\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

 80%|████████  | 1664/2080 [18:18<02:16,  3.04it/s]

{'eval_loss': 0.6949778199195862, 'eval_accuracy': 0.5, 'eval_precision_pos': 0.0, 'eval_recall_pos': 0.0, 'eval_f1_pos': 0.0, 'eval_tn': 89, 'eval_fp': 0, 'eval_fn': 89, 'eval_tp': 0, 'eval_runtime': 1.2195, 'eval_samples_per_second': 145.966, 'eval_steps_per_second': 18.861, 'epoch': 16.0}

 82%|████████▏ | 1701/2080 [19:24<02:15,  2.80it/s]

{'loss': 0.7038, 'learning_rate': 3.9897698209718675e-06, 'epoch': 16.35}

 84%|████████▍ | 1751/2080 [19:43<01:51,  2.95it/s]

{'loss': 0.7069, 'learning_rate': 3.4782608695652175e-06, 'epoch': 16.83}

 85%|████████▌ | 1768/2080 [19:51<02:12,  2.35it/s]

{'eval_loss': 0.6944758296012878, 'eval_accuracy': 0.4943820224719101, 'eval_precision_pos': 0.0, 'eval_recall_pos': 0.0, 'eval_f1_pos': 0.0, 'eval_tn': 88, 'eval_fp': 1, 'eval_fn': 89, 'eval_tp': 0, 'eval_runtime': 1.0272, 'eval_samples_per_second': 173.283, 'eval_steps_per_second': 22.391, 'epoch': 17.0}

 87%|████████▋ | 1800/2080 [20:13<01:57,  2.39it/s]

{'loss': 0.6856, 'learning_rate': 2.966751918158568e-06, 'epoch': 17.31}

 89%|████████▉ | 1850/2080 [20:32<01:11,  3.21it/s]

{'loss': 0.7132, 'learning_rate': 2.4552429667519184e-06, 'epoch': 17.79}

 90%|█████████ | 1872/2080 [20:41<01:10,  2.95it/s]

{'eval_loss': 0.6955347061157227, 'eval_accuracy': 0.4943820224719101, 'eval_precision_pos': 0.47619047619047616, 'eval_recall_pos': 0.11235955056179775, 'eval_f1_pos': 0.18181818181818182, 'eval_tn': 78, 'eval_fp': 11, 'eval_fn': 79, 'eval_tp': 10, 'eval_runtime': 1.2395, 'eval_samples_per_second': 143.602, 'eval_steps_per_second': 18.555, 'epoch': 18.0}

 91%|█████████▏| 1900/2080 [21:34<01:07,  2.66it/s]

{'loss': 0.7181, 'learning_rate': 1.9437340153452684e-06, 'epoch': 18.27}

 94%|█████████▍| 1950/2080 [21:53<00:50,  2.57it/s]

{'loss': 0.7008, 'learning_rate': 1.432225063938619e-06, 'epoch': 18.75}

 95%|█████████▌| 1976/2080 [22:04<00:41,  2.53it/s]

{'eval_loss': 0.693822979927063, 'eval_accuracy': 0.4943820224719101, 'eval_precision_pos': 0.0, 'eval_recall_pos': 0.0, 'eval_f1_pos': 0.0, 'eval_tn': 88, 'eval_fp': 1, 'eval_fn': 89, 'eval_tp': 0, 'eval_runtime': 1.0043, 'eval_samples_per_second': 177.236, 'eval_steps_per_second': 22.901, 'epoch': 19.0}

 96%|█████████▌| 2000/2080 [22:22<00:26,  3.07it/s]

{'loss': 0.6861, 'learning_rate': 9.207161125319694e-07, 'epoch': 19.23}

 99%|█████████▊| 2050/2080 [22:41<00:11,  2.53it/s]

{'loss': 0.7145, 'learning_rate': 4.0920716112531976e-07, 'epoch': 19.71}

100%|██████████| 2080/2080 [22:54<00:00,  2.88it/s]

{'eval_loss': 0.693351149559021, 'eval_accuracy': 0.5, 'eval_precision_pos': 0.5, 'eval_recall_pos': 0.8876404494382022, 'eval_f1_pos': 0.6396761133603239, 'eval_tn': 10, 'eval_fp': 79, 'eval_fn': 10, 'eval_tp': 79, 'eval_runtime': 1.1066, 'eval_samples_per_second': 160.86, 'eval_steps_per_second': 20.785, 'epoch': 20.0}

100%|██████████| 2080/2080 [23:49<00:00,  1.46it/s]

{'train_runtime': 1429.0865, 'train_samples_per_second': 11.56, 'train_steps_per_second': 1.455, 'train_loss': 0.713957405090332, 'epoch': 20.0}

TrainOutput(global_step=2080, training_loss=0.713957405090332, metrics={'train_runtime': 1429.0865, 'train_samples_per_second': 11.56, 'train_steps_per_second': 1.455, 'train_loss': 0.713957405090332, 'epoch': 20.0})

In [12]:
# Cell 9 — Evaluate on validation + test
# ---------------------------------------------------------------
print("Best checkpoint:", trainer.state.best_model_checkpoint)

val_metrics = trainer.evaluate(val_tok)
print("\nVAL metrics:")
for k, v in val_metrics.items():
    if k.startswith("eval_"):
        print(f"{k}: {v}")

test_metrics = trainer.evaluate(test_tok)
print("\nTEST metrics:")
for k, v in test_metrics.items():
    if k.startswith("eval_"):
        print(f"{k}: {v}")

Best checkpoint: runs_tashbeeh/aubmindlab_bert-large-arabertv2\checkpoint-728

100%|██████████| 23/23 [00:00<00:00, 23.61it/s]

VAL metrics:
eval_loss: 0.6970489025115967
eval_accuracy: 0.5
eval_precision_pos: 0.5
eval_recall_pos: 1.0
eval_f1_pos: 0.6666666666666666
eval_tn: 0
eval_fp: 89
eval_fn: 0
eval_tp: 89
eval_runtime: 1.1471
eval_samples_per_second: 155.18
eval_steps_per_second: 20.051

100%|██████████| 23/23 [00:00<00:00, 23.38it/s]

TEST metrics:
eval_loss: 0.6954743266105652
eval_accuracy: 0.5
eval_precision_pos: 0.5
eval_recall_pos: 1.0
eval_f1_pos: 0.6666666666666666
eval_tn: 0
eval_fp: 89
eval_fn: 0
eval_tp: 89
eval_runtime: 1.0295
eval_samples_per_second: 172.898
eval_steps_per_second: 22.341

In [13]:
# Cell 10 — Predict on test set + show some errors (false positives/negatives)
# ---------------------------------------------------------------
pred_out = trainer.predict(test_tok)
test_logits = pred_out.predictions
test_preds = np.argmax(test_logits, axis=-1)
test_labels = pred_out.label_ids

# Rebuild a viewable df aligned with test_df order
view_df = pd.DataFrame({
    TEXT_COL: test_ds[TEXT_COL],
    "y_true": test_labels,
    "y_pred": test_preds,
})

# Show false negatives (missed tashbeeh)
fn_df = view_df[(view_df["y_true"] == 1) & (view_df["y_pred"] == 0)].head(15)
fp_df = view_df[(view_df["y_true"] == 0) & (view_df["y_pred"] == 1)].head(15)

print("False Negatives (missed tashbeeh):", fn_df.shape[0])
display(fn_df)

print("False Positives (predicted tashbeeh but actually non):", fp_df.shape[0])
display(fp_df)

100%|██████████| 23/23 [00:00<00:00, 23.62it/s]

False Negatives (missed tashbeeh): 0

Empty DataFrame
Columns: [البيت_الكامل, y_true, y_pred]
Index: []

False Positives (predicted tashbeeh but actually non): 15

                                         البيت_الكامل  y_true  y_pred
1   ومهمهٍ نازحٍ ، تعوي الذئابُ به، نائي المياهِ ع...       0       1
2   بَلْ عَجِبُوا أَنْ جَاءَهُمْ مُنْذِرٌ مِنْهُمْ...       0       1
4   فإن أكُ مظلوماً؛ فعبدٌ ظلمتَهُ؛ وإن تكُ ذا عُت...       0       1
6   لأْيًا يُجَاهِدُهَا لا يَأْتَلِي طَلَبًا لأْيً...       0       1
7   كَرِيمًا حِينَ يُنْسَبُ والِدَاهُ إلَى كَرَمِ ...       0       1
12  يا طَلْعَةً طَلَعَ الحِمامُ عليها وجنى لها ثَم...       0       1
13  لم يَبْقَ لِلصَّيْفِ لا رَسْمٌ ولا طَلَلُ ولا ...       0       1
15  حَكَمَتْ لأَنْفُسِها اللَّيالي أَنَّها أَبداً ...       0       1
17  إِنَّا نَحْنُ نُحْيِي وَنُمِيتُ وَإِلَيْنَا ال...       0       1
19  وَكُنَّا إِذَا ما خَانَنَا الدَّهْرُ أوْ سَرَى...       0       1
20  زعمَ الـهُمامُ، ولم أذُقْه، أنّهُ يُشفي، بريّا...       0       1
22  [أبْكيكُمُ يا بَني التَّقْوى وأُعْوِلُكُمْ وأش...       0       1
24  فمدَّت يدًا في حُسْنِ كلٍّ تناولًا إليه وقالت:...       0       1
26  حَامِي الحَقِيقَةِ نَسَّالُ الوَدِيقَةِ مِعْتَ...       0       1
27  أَخي ثِقَةٍ لا يَنْثَني عَنْ ضَرِيبَةٍ إِذا قي...       0       1

In [14]:
# Cell 11 — Save the best model + tokenizer (for later inference)
# ---------------------------------------------------------------
BEST_DIR = os.path.join(OUTPUT_DIR, "best_model")
trainer.save_model(BEST_DIR)
tokenizer.save_pretrained(BEST_DIR)
print("Saved to:", BEST_DIR)

Saved to: runs_tashbeeh/aubmindlab_bert-large-arabertv2\best_model

In [15]:
# Cell 12 — Quick inference function (single verse)
# ---------------------------------------------------------------
import torch

def predict_tashbeeh(verse: str) -> int:
    model.eval()
    enc = tokenizer(verse, return_tensors="pt", truncation=True, max_length=MAX_LEN).to(device)
    with torch.no_grad():
        logits = model(**enc).logits
    pred = int(torch.argmax(logits, dim=-1).item())
    return pred  # 1=tashbeeh, 0=non

# Example:
# print(predict_tashbeeh("أهُمُّ بِشَيْءٍ واللَّيالي كأنَّهَا تُطارِدُنِي"))